---
- name: Install common packages
  apt:
    update_cache: yes
    pkg:
      - jq
      - ansible
      - openjdk-8-jdk-headless
      - git
      - git-lfs
      - nvme-cli
      - ntp
      - build-essential
      - wget
      - curl
      - vim
      - screen
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - unzip
      - sudo

- name: Initialize git-lfs
  command: git lfs install
  vars:
    ansible_become: no

- name: Upgrade pip
  pip:
    executable: pip3
    extra_args: --upgrade
    name:
      - pip

- name: Install pip packages
  pip:
    executable: pip3
    name:
      - requests
      - PyYaml
      - jinja2

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Create /etc/sudoers.d/wheel
  copy:
    content: "%wheel ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/wheel
    group: root
    owner: root
    mode: '0440'

- name: Create ubuntu user
  user:
    name: ubuntu
    uid: 1000

- name: Add authorized keys
  authorized_key:
    user: ubuntu
    key: '{{ item }}'
  with_file:
    - goai-gpuci.id_rsa.pub
    - jenkins-master.id_rsa.pub
    - jenkins-aws-master.id_rsa.pub

- name: Create ubuntu home directory if not exists
  file:
    path: /home/ubuntu
    state: directory

- name: Download awscli
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /home/ubuntu/
    remote_src: yes

- name: Install awscli
  command: /home/ubuntu/aws/install

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: Create rc.local
  copy:
    dest: /etc/rc.local
    mode: '0555'
    content: |
      #!/bin/bash
      